apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: spring-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: springapp-image
  policy:
    numerical:
      order: asc
