apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - ../../base/jenkins/jenkins-namespace.yaml
  - ../../base/jenkins/jenkins-chart.yaml
configMapGenerator:
  - name: jenkins-values
    files:
      - values.yaml=../values_jen.yaml
configurations:
  - ../../base/jenkins/kustomizeconfig.yaml
