apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/springapp
- image-policy.yml
- image.yml  
namespace: dev
patches:
 - path: my-dep-patch.yml
   target:
    kind: Deployment
