apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: spring
        image: htyagi/spring:5.0 # {"$imagepolicy": "flux-system:spring-image-policy"}
