apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: dev
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: spring
        image: htyagi/spring:2.0 # {"$imagepolicy": "flux-system:spring-image-policy"}
